#!/usr/bin/python2
# WMI replication AD checker

import math
import sys
import argparse
from pywmi_wbem.wsman.query import WSMan, WSManFault

if __name__ == '__main__':

  parser = argparse.ArgumentParser(description='WMI replication AD checker')
  parser.add_argument('-H', '--host', help="Hostname to check", type=str, required=True)
  parser.add_argument('-S', '--ssl', help="Use a TLS connection", action='store_true')

  args = parser.parse_args()

  query="SELECT LastSyncResult, NamingContextDN, NumConsecutiveSyncFailures, SourceDsaCN from MSAD_ReplNeighbor"

  wsman = WSMan(args.host, tls=args.ssl)

  try:
    out=wsman.search_wql(query, namespace="root/MicrosoftActiveDirectory")
  except WSManFault as err:
    print("UNKNOWN: WSManFault: %s " % (err.message))
    sys.exit(3)
  except Exception as err:
    print("UNKNOWN: %s: %s" % (type(err).__name__, err))
    sys.exit(3)

  if len(out) == 0:
    print("UNKNOWN: No data returned")
    sys.exit(3)

ret_status = 2

for obj in out :
    LastSyncResult = obj["LastSyncResult"]
    SourceDsaCN = obj["SourceDsaCN"]
    NumConsecutiveSyncFailures = obj["NumConsecutiveSyncFailures"]
    if LastSyncResult != 0:
       ret_status = 1
       print "CRITICAL: Replication fail" , SourceDsaCN , NumConsecutiveSyncFailures
       sys.exit(ret_status)
    ret_status = LastSyncResult

if ret_status != 2:
   print "OK: Replication successful"
   sys.exit(ret_status)
else:
   print "WARNING: Script fail"
   sys.exit(ret_status)
